import type {
  Patient,
  DashboardStats,
  AdmissionTrend,
  DepartmentLoad,
  StatusDistribution,
  WeeklyVitalsAvg,
  DemoNotif,
} from "@medicare-pro/types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p-001",
    mrn: "MRN-2026-001",
    firstName: "Ananya",
    lastName: "Sharma",
    fullName: "Ananya Sharma",
    age: 45,
    gender: "female",
    bloodGroup: "A+",
    status: "stable",
    department: "Cardiology",
    ward: "Ward 3A",
    bedNumber: "301",
    admissionDate: "2026-06-15T08:30:00Z",
    diagnosis: "Hypertension, Type 2 Diabetes",
    treatingPhysician: "Dr. James Harrington",
    phoneNumber: "+91 98450 12345",
    email: "ananya.sharma@email.com",
    address: "123, Indiranagar 100ft Road, Bangalore, KA 560038",
    emergencyContact: {
      name: "Rahul Sharma",
      relationship: "Husband",
      phone: "+91 98450 12346",
    },
    vitals: {
      heartRate: 72,
      bloodPressure: "128/82",
      temperature: 98.6,
      oxygenSaturation: 98,
      respiratoryRate: 16,
    },
    medications: ["Metformin 500mg", "Lisinopril 10mg", "Atorvastatin 20mg"],
    allergies: ["Penicillin"],
    insuranceProvider: "Star Health Insurance",
    insuranceId: "STAR-445-8821",
    notes: "Patient responds well to current medication regimen.",
  },
  {
    id: "p-002",
    mrn: "MRN-2026-002",
    firstName: "Rajesh",
    lastName: "Kumar",
    fullName: "Rajesh Kumar",
    age: 62,
    gender: "male",
    bloodGroup: "O+",
    status: "critical",
    department: "Intensive Care",
    ward: "ICU",
    bedNumber: "ICU-04",
    admissionDate: "2026-07-01T14:20:00Z",
    diagnosis: "Acute Myocardial Infarction",
    treatingPhysician: "Dr. Elena Vasquez",
    phoneNumber: "+91 99001 23456",
    email: "rkumar@email.com",
    address: "567, Marine Drive, Mumbai, MH 400002",
    emergencyContact: {
      name: "Suman Kumar",
      relationship: "Wife",
      phone: "+91 99001 23457",
    },
    vitals: {
      heartRate: 108,
      bloodPressure: "95/60",
      temperature: 99.8,
      oxygenSaturation: 91,
      respiratoryRate: 24,
    },
    medications: [
      "Aspirin 325mg",
      "Heparin IV",
      "Nitroglycerin",
      "Morphine 2mg",
    ],
    allergies: ["Sulfa drugs", "Latex"],
    insuranceProvider: "HDFC ERGO",
    insuranceId: "HDFC-771-2234",
    notes: "Critical: hourly vitals monitoring required. Family notified.",
  },
  {
    id: "p-003",
    mrn: "MRN-2026-003",
    firstName: "Priya",
    lastName: "Iyer",
    fullName: "Priya Iyer",
    age: 38,
    gender: "female",
    bloodGroup: "B+",
    status: "recovering",
    department: "Orthopedics",
    ward: "Ward 5B",
    bedNumber: "512",
    admissionDate: "2026-06-28T10:00:00Z",
    diagnosis: "Right Hip Fracture post-op",
    treatingPhysician: "Dr. Michael Torres",
    phoneNumber: "+91 94440 34567",
    email: "piyer@email.com",
    address: "890, Anna Salai, Chennai, TN 600002",
    emergencyContact: {
      name: "Karthik Iyer",
      relationship: "Brother",
      phone: "+91 94440 34568",
    },
    vitals: {
      heartRate: 78,
      bloodPressure: "118/76",
      temperature: 99.1,
      oxygenSaturation: 97,
      respiratoryRate: 17,
    },
    medications: ["Oxycodone 5mg", "Enoxaparin 40mg", "Calcium Carbonate"],
    allergies: [],
    insuranceProvider: "ICICI Lombard",
    insuranceId: "ICICI-556-9913",
    notes: "PT sessions scheduled daily. Pain management improving.",
  },
  {
    id: "p-004",
    mrn: "MRN-2026-004",
    firstName: "Vikram",
    lastName: "Singh",
    fullName: "Vikram Singh",
    age: 55,
    gender: "male",
    bloodGroup: "AB-",
    status: "stable",
    department: "Neurology",
    ward: "Ward 2C",
    bedNumber: "224",
    admissionDate: "2026-07-03T09:15:00Z",
    diagnosis: "Ischemic Stroke, mild",
    treatingPhysician: "Dr. Priya Sharma",
    phoneNumber: "+91 98100 45678",
    email: "vsingh@email.com",
    address: "234, Connaught Place, New Delhi, DL 110001",
    emergencyContact: {
      name: "Meena Singh",
      relationship: "Wife",
      phone: "+91 98100 45679",
    },
    vitals: {
      heartRate: 68,
      bloodPressure: "135/88",
      temperature: 98.4,
      oxygenSaturation: 96,
      respiratoryRate: 15,
    },
    medications: ["Aspirin 81mg", "Clopidogrel 75mg", "Rosuvastatin 40mg"],
    allergies: ["Ibuprofen"],
    insuranceProvider: "Niva Bupa",
    insuranceId: "NIVA-334-7762",
    notes: "Speech therapy initiated. MRI follow-up scheduled in 48h.",
  },
  {
    id: "p-005",
    mrn: "MRN-2026-005",
    firstName: "Kavita",
    lastName: "Reddy",
    fullName: "Kavita Reddy",
    age: 29,
    gender: "female",
    bloodGroup: "O-",
    status: "discharged",
    department: "General Medicine",
    ward: "Ward 1A",
    bedNumber: "104",
    admissionDate: "2026-06-20T11:45:00Z",
    dischargeDate: "2026-06-25T14:00:00Z",
    diagnosis: "Acute Appendicitis post-op",
    treatingPhysician: "Dr. Samuel Wright",
    phoneNumber: "+91 98480 56789",
    email: "kreddy@email.com",
    address: "456, Jubilee Hills, Hyderabad, TS 500033",
    emergencyContact: {
      name: "Saritha Reddy",
      relationship: "Mother",
      phone: "+91 98480 56790",
    },
    vitals: {
      heartRate: 74,
      bloodPressure: "112/70",
      temperature: 98.2,
      oxygenSaturation: 99,
      respiratoryRate: 14,
    },
    medications: ["Amoxicillin-Clavulanate", "Ibuprofen 400mg"],
    allergies: [],
    insuranceProvider: "Apollo Munich",
    insuranceId: "APO-882-1145",
    notes: "Discharged with follow-up in 2 weeks.",
  },
  {
    id: "p-006",
    mrn: "MRN-2026-006",
    firstName: "Arjun",
    lastName: "Mehta",
    fullName: "Arjun Mehta",
    age: 71,
    gender: "male",
    bloodGroup: "A-",
    status: "critical",
    department: "Pulmonology",
    ward: "ICU",
    bedNumber: "ICU-07",
    admissionDate: "2026-07-04T07:00:00Z",
    diagnosis: "Severe Pneumonia, ARDS",
    treatingPhysician: "Dr. Elena Vasquez",
    phoneNumber: "+91 98230 67890",
    email: "amehta@email.com",
    address: "789, Koregaon Park, Pune, MH 411001",
    emergencyContact: {
      name: "Anita Mehta",
      relationship: "Daughter",
      phone: "+91 98230 67891",
    },
    vitals: {
      heartRate: 115,
      bloodPressure: "88/55",
      temperature: 101.4,
      oxygenSaturation: 88,
      respiratoryRate: 28,
    },
    medications: [
      "Ceftriaxone 2g IV",
      "Azithromycin 500mg",
      "Dexamethasone 6mg",
      "Vancomycin 1g",
    ],
    allergies: ["Aspirin", "Codeine"],
    insuranceProvider: "PM-JAY (Ayushman Bharat)",
    insuranceId: "PMJAY-991-4456",
    notes: "On mechanical ventilation. Family at bedside.",
  },
  {
    id: "p-007",
    mrn: "MRN-2026-007",
    firstName: "Sneha",
    lastName: "Kapoor",
    fullName: "Sneha Kapoor",
    age: 44,
    gender: "female",
    bloodGroup: "B-",
    status: "recovering",
    department: "Oncology",
    ward: "Ward 4D",
    bedNumber: "411",
    admissionDate: "2026-06-10T13:30:00Z",
    diagnosis: "Breast Cancer Stage II, Chemotherapy Cycle 3",
    treatingPhysician: "Dr. Marcus Holloway",
    phoneNumber: "+91 99100 78901",
    email: "skapoor@email.com",
    address: "321, DLF Phase 3, Gurgaon, HR 122002",
    emergencyContact: {
      name: "Kevin Kapoor",
      relationship: "Husband",
      phone: "+91 99100 78902",
    },
    vitals: {
      heartRate: 82,
      bloodPressure: "110/72",
      temperature: 98.9,
      oxygenSaturation: 97,
      respiratoryRate: 16,
    },
    medications: [
      "Doxorubicin",
      "Cyclophosphamide",
      "Ondansetron 8mg",
      "Filgrastim",
    ],
    allergies: ["Contrast dye"],
    insuranceProvider: "Bajaj Allianz",
    insuranceId: "BAJAJ-667-3321",
    notes:
      "Tolerating chemo cycle 3 better than cycle 2. Oncology team pleased.",
  },
  {
    id: "p-008",
    mrn: "MRN-2026-008",
    firstName: "Rahul",
    lastName: "Deshmukh",
    fullName: "Rahul Deshmukh",
    age: 58,
    gender: "male",
    bloodGroup: "AB+",
    status: "stable",
    department: "Gastroenterology",
    ward: "Ward 3B",
    bedNumber: "318",
    admissionDate: "2026-07-02T16:00:00Z",
    diagnosis: "Crohn's Disease flare-up",
    treatingPhysician: "Dr. Sandra Kim",
    phoneNumber: "+91 98300 89012",
    email: "rdeshmukh@email.com",
    address: "654, Park Street, Kolkata, WB 700016",
    emergencyContact: {
      name: "Priya Deshmukh",
      relationship: "Wife",
      phone: "+91 98300 89013",
    },
    vitals: {
      heartRate: 76,
      bloodPressure: "122/80",
      temperature: 99.0,
      oxygenSaturation: 98,
      respiratoryRate: 16,
    },
    medications: ["Infliximab 300mg IV", "Prednisone 40mg", "Mesalamine 800mg"],
    allergies: [],
    insuranceProvider: "Care Health Insurance",
    insuranceId: "CARE-443-8877",
    notes:
      "Infliximab infusion planned for tomorrow. Diet restricted to clear liquids.",
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalPatients: 247,
  criticalAlerts: 8,
  admissionsToday: 12,
  dischargesThisWeek: 34,
  averageOccupancy: 87,
  pendingLabResults: 23,
};

export const MOCK_ADMISSION_TRENDS: AdmissionTrend[] = [
  { month: "Jan", admissions: 186, discharges: 172 },
  { month: "Feb", admissions: 205, discharges: 198 },
  { month: "Mar", admissions: 237, discharges: 225 },
  { month: "Apr", admissions: 218, discharges: 230 },
  { month: "May", admissions: 262, discharges: 244 },
  { month: "Jun", admissions: 289, discharges: 271 },
  { month: "Jul", admissions: 247, discharges: 213 },
];

export const MOCK_DEPARTMENT_LOAD: DepartmentLoad[] = [
  { department: "Cardiology", patients: 48, capacity: 60 },
  { department: "Intensive Care", patients: 22, capacity: 24 },
  { department: "Orthopedics", patients: 35, capacity: 45 },
  { department: "Neurology", patients: 31, capacity: 40 },
  { department: "Oncology", patients: 42, capacity: 50 },
  { department: "Pulmonology", patients: 28, capacity: 35 },
  { department: "General Medicine", patients: 41, capacity: 55 },
];

export const MOCK_STATUS_DISTRIBUTION: StatusDistribution[] = [
  { status: "stable", count: 142 },
  { status: "recovering", count: 67 },
  { status: "critical", count: 18 },
  { status: "discharged", count: 20 },
];

export const MOCK_WEEKLY_VITALS: WeeklyVitalsAvg[] = [
  { day: "Mon", heartRate: 74, bloodPressure: 80 },
  { day: "Tue", heartRate: 77, bloodPressure: 82 },
  { day: "Wed", heartRate: 73, bloodPressure: 79 },
  { day: "Thu", heartRate: 79, bloodPressure: 84 },
  { day: "Fri", heartRate: 76, bloodPressure: 81 },
  { day: "Sat", heartRate: 72, bloodPressure: 78 },
  { day: "Sun", heartRate: 71, bloodPressure: 77 },
];

export const DEMO_NOTIFICATIONS: DemoNotif[] = [
  {
    id: "n-001",
    type: "critical",
    title: "Critical Vital Alert",
    message: "Rajesh Kumar (ICU-04) heart rate exceeded 105 bpm.",
    time: "2 mins ago",
    read: false,
  },
  {
    id: "n-002",
    type: "admission",
    title: "New Admission",
    message: "Rahul Deshmukh admitted to Gastroenterology.",
    time: "15 mins ago",
    read: false,
  },
  {
    id: "n-003",
    type: "lab",
    title: "Lab Results Ready",
    message: "CBC results available for Ananya Sharma.",
    time: "1 hour ago",
    read: true,
  },
];
